### ISSUE TITLE
fetch nation's

### ISSUE THREAD

**Issue by florianlenz** [Bit-Nation/nation-framework#3]
## Feature
Since I need to filter the nation's on the user device I would like to have a function that return's a set of nation data (not all data, only important data for search like the name).

## Acceptance Criteria
- [ ] function that fetch set of nation's. Returned data should be the nation name, count of members and an identifier which allowes us to fetch the whole nation data by an ID (that's it for now)..

**Comment by william2958** [comment]
This will be better implemented in the javascript side using the already existing getNationCore method. I can create a getNationCoreById if that's better. This is because I cannot return an array of strings for the nation names, since that is not supported in solidity.

**Comment by florianlenz** [comment]
@william2958 `getNationCore` expect's the nation name which is a kind of ID right? But for auto completion I need a way to fetch a set of nation's and check there name. Maybe we can do smth like [this]( https://ethereum.stackexchange.com/questions/17312/solidity-can-you-return-dynamic-arrays-in-a-function)?

What's about "static" array's? Can we have smth like `get50Nations(uint _start)`? Which return's 50 nation's from a special start index? And then smth like `get20Nations(uint _start)` (also 10, 5, 2, 1)

**Comment by florianlenz** [comment]
And a method to get the count of nation's.

**Comment by florianlenz** [comment]
Wait does that mean that we also can't return all member's of a nation since it's an dynamic array?

**Comment by william2958** [comment]
Ok so you can get the number of nations using the public variable numNations. From there you can, in javascript, write something like:

for (int i=0; i<numNations; i++) {
nations.push(contract.getNation(contract.getNationName(i)))
}

* written in pseudocode, and getNationName is a function I just added, forgot to add it on the first run through.

And members are not handled in the nation as of yet. We need to figure out if we want to do that in the nations contract or within their own separate citizens contract.

**Comment by florianlenz** [comment]
Ok sure, my only concern is that we have todo a lot of web3 request's in order to fetch all nation's ... but we can try it. 

Yeah we should definitely do that asap.
